apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}-querier
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: querier
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.querier.service.type }}
  {{- if (or (eq .Values.querier.service.type "LoadBalancer") (eq .Values.querier.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.querier.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.querier.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.querier.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.querier.service.type "LoadBalancer") (not (empty .Values.querier.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.querier.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.querier.service.port }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.querier.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: querier
